import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "src/components/Layout";
import profilePic from "~/images/profile/hugo.jpeg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import HireMe from "@/components/HireMe";
import lightBulb from "~/images/svgs/miscellaneous_icons_1.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hugo Dorfling | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Hugo Dorfling"
                className="w-full h-auto rounded-full"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left dark:text-light"
              />
              <p className="my-4 text-base font-medium">
                I have about 3 years experience in Digital Product Development
                from 3 startups (Seed & Development, Startup and Growth business
                stages respectively) serving in roles as Technical Product
                Manager, Full Stack Engineer, Front-End Engineer, UI / UX (Figma
                & Miro) and Cloud (3x AWS Certified) with Agile Scrum and Kanban
                product development framework.
              </p>
              <p>
                I strive to create value while living a meaningful and purpose
                driven life.
              </p>
              <p className="my-4 text-base font-medium">
                I love to collaborate in order to solve complex problems in
                order to make a lasting impact. Experimentation, innovation,
                feedback, iteration and improvement are main drivers of my
                exhilarating passion to find disruptive and elegant solutions
                presented in delightful experiences.
              </p>
              <p className="my-4 text-base font-medium">
                I have done studies in BCom Informatics and BSc Computer
                Science, both incomplete degrees, and I’ve discovered, through
                practical work experience, on real products, where I add the
                most value. I combine my years of experience as Graphic Designer
                in my youth, with my communication skills gained through
                Counseling / Church Ministry, Analysis and Systems & Design
                Thinking from BCom Informatics studies, Technical Acumen from my
                IT experience and Software Product Engineering and Computer
                Science from my years as a Software Engineer into a role that
                focuses on bringing all areas of product development and
                business together to make remarkable and life-changing products
                that make a difference in peoples lives through servant
                leadership, collaboration and strong determination towards
                realizing a worthwhile vision.
              </p>
              <p className="my-4 text-base font-medium">
                I thrive in a highly autonomous and collaborative environment
                where discovery, exploration and learning are highly valued
                through the three pillars of empiricism, namely Transparency,
                Inspection and Adaptation. I care deeply about truly connecting
                with fellow humans and building lasting relationships that are
                meaningful through empathy and love.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark
                  border border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:hugodorfling@live.co.za"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Projects / Portfolio
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div
          className="absolute 
        right-8 bottom-8 inline-block w-24"
        >
          <Image src={lightBulb} alt="Hugo" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
